In [2]:
import torch

In [3]:
import torch.nn as nn

In [103]:
layer_1 = nn.Conv2d(in_channels=1, out_channels=5, kernel_size=(3, 1), padding=0, bias=False)

In [21]:
input_1 = torch.randn(1, 10, 20)

In [104]:
input_1 = torch.tensor([[[1,2,3,4],[4,5,6,7],[7,8,9,10]]], dtype=torch.float32)

In [105]:
output = layer_1(input_1)

In [106]:
layer_1._parameters['weight']

Parameter containing:
tensor([[[[ 0.3945],
          [ 0.2567],
          [-0.2379]]],


        [[[-0.5697],
          [ 0.0806],
          [ 0.3012]]],


        [[[-0.4768],
          [ 0.0312],
          [ 0.1379]]],


        [[[ 0.2283],
          [-0.2077],
          [-0.2307]]],


        [[[ 0.4731],
          [ 0.0743],
          [ 0.0610]]]], requires_grad=True)

In [107]:
print(input_1.shape)
print(layer_1._parameters['weight'].shape)
print(output.shape)
output

torch.Size([1, 3, 4])
torch.Size([5, 1, 3, 1])
torch.Size([5, 1, 4])

tensor([[[-2.4364e-01,  1.6972e-01,  5.8309e-01,  9.9645e-01]],

        [[ 1.8612e+00,  1.6733e+00,  1.4854e+00,  1.2975e+00]],

        [[ 6.1341e-01,  3.0567e-01, -2.0745e-03, -3.0982e-01]],

        [[-2.2174e+00, -2.4275e+00, -2.6377e+00, -2.8478e+00]],

        [[ 1.1976e+00,  1.8060e+00,  2.4144e+00,  3.0229e+00]]],
       grad_fn=<SqueezeBackward1>)

In [108]:
with torch.no_grad():
    print((layer_1._parameters['weight'][2][0] * input_1[0][:, 2].view(-1,1)).sum())

tensor(-0.0021)

In [74]:
input_1[0][:, 0].view(-1,1)

tensor([[1.],
        [4.],
        [7.]])

In [67]:
layer_1._parameters['weight'][0][0]

tensor([[-0.3253],
        [-0.4667],
        [-0.4166]], grad_fn=<SelectBackward0>)

In [78]:
(torch.tensor([[1,2,3]]).T * torch.tensor([[4,5,6]]).T).sum()

tensor(32)

In [76]:
torch.tensor([[1,2,3]]).shape

torch.Size([1, 3])

In [110]:
output

tensor([[[-2.4364e-01,  1.6972e-01,  5.8309e-01,  9.9645e-01]],

        [[ 1.8612e+00,  1.6733e+00,  1.4854e+00,  1.2975e+00]],

        [[ 6.1341e-01,  3.0567e-01, -2.0745e-03, -3.0982e-01]],

        [[-2.2174e+00, -2.4275e+00, -2.6377e+00, -2.8478e+00]],

        [[ 1.1976e+00,  1.8060e+00,  2.4144e+00,  3.0229e+00]]],
       grad_fn=<SqueezeBackward1>)

In [127]:
review_length = 10
word_embed_dim = 8
num_conv_filters = 15
conv_filter_size = word_embed_dim
id_embed_dim = 12
batch_size = 1

num_reviews = 13 # lets assume user has 13 reviews; this number varies from user to user
test_input = torch.randn(num_reviews, 1, word_embed_dim, review_length)

In [128]:

c_j = nn.Conv2d(in_channels=1, out_channels=num_conv_filters, kernel_size=(word_embed_dim, 1), padding=0, bias=True)
c_u_k = c_j(test_input)

In [151]:
w_w = torch.randn(review_length, id_embed_dim)
q_i = torch.randn(id_embed_dim, 1) 
beta_k = torch.matmul(w_w, q_i)

b_1 = torch.randn(review_length, review_length)

In [152]:
b_1.shape

torch.Size([10, 10])

In [157]:
beta_k.shape

torch.Size([10, 1])

In [155]:
y_c_times_b_1 = torch.matmul(c_u_k, b_1)
y_c_times_b_1.shape

torch.Size([13, 15, 1, 10])

In [162]:
b_c = beta_k @ y_c_times_b_1
b_c.shape

torch.Size([13, 15, 10, 10])

In [163]:
b_c.shape

torch.Size([13, 15, 10, 10])

In [156]:
c_u_k.shape

torch.Size([13, 15, 1, 10])

In [145]:
w_w.shape, q_i.shape

(torch.Size([10, 12]), torch.Size([12, 1]))

In [129]:
c_u_k.shape

torch.Size([13, 15, 1, 10])

In [136]:
test_input.shape, c_j._parameters['weight'].shape

(torch.Size([13, 1, 8, 10]), torch.Size([15, 1, 8, 1]))

In [178]:

# single review
c_j = torch.randn(num_conv_filters, review_length)

num_users = 100
id_embedding = nn.Embedding(num_users, id_embed_dim)

user_id = torch.tensor([0])
user_embedding = id_embedding(user_id)


w_w = torch.randn(review_length, id_embed_dim)
beta_k = torch.matmul(w_w, user_embedding.view(id_embed_dim, -1)) # review_length * 1

print(f'beta_k shape - {beta_k.shape}')

B_1 = torch.randn(review_length, review_length)
b_c = c_j @ B_1 # num_conv_filters * review_length



alpha = # 1 * review_length
d_uk = # 1 * review_length or review_length * 1

beta_k shape - torch.Size([10, 1])

In [168]:
id_embedding.weight[1].shape

torch.Size([12])

In [174]:
id_embedding(user_id[0]).unsqueeze(0)

torch.Size([1, 12])

In [ ]:
# review_length * num_conv_filters, num_conv_filters * 1
# result - review_length * 1
# b_c - 1 * review_length, review_length * 1
# alpha_c - 
# 1 * review_length

# 
# d_uk =>

In [ ]:

# c_uk => num_conv_filters * review_length

# c_uk to d_uk using alpha

# b_c => review_length * 1 , review_length * num_conv_filters, num_conv_filters * 1
# alpha => 1 * review_length
# d_uk => 1 * review_length (element wise product across columns ??) 
        # num_conv_filters * review_length


# c_uk => num_conv_filters * review_length
# b_c => 1 * review_length => (review_length * 1).T, review_length * num_conv_filters, num_conv_filters * review_length
# alpha => 1 * review_length
# d_uk => 1 * num_conv_filters

In [308]:
# keep user reviews and item reviews separately??

import pandas as pd

df = pd.read_csv("../data/books_mini_sample.csv")

In [314]:
filtered_df = df[['rating', 'text', 'user_id', 'asin']].copy()
filtered_df.head()

,rating,text,user_id,asin
0,5.0,This is a great book with a lot of detail. ON...,AE224GVO7OHTYF26U6ER6BEVIUAQ,0486241386
1,5.0,Ladies 'n Gentlemen...we have another hit from...,AE225Z2VRWT6GPTOMA4H4O3H2KVQ,B000MGATTE
2,5.0,I ordered this book for my Kindle. Koontz and ...,AE225Z2VRWT6GPTOMA4H4O3H2KVQ,B000UDNBRQ
3,5.0,Absolutely loved this book! Stephen King just...,AE225Z2VRWT6GPTOMA4H4O3H2KVQ,B000UZJREU
4,5.0,Another King satisfied reader~! what can I sa...,AE225Z2VRWT6GPTOMA4H4O3H2KVQ,B001RF3U9K

In [315]:
filtered_df.dtypes

rating     float64
text        object
user_id     object
asin        object
dtype: object

In [316]:
filtered_df['user_id'] = filtered_df['user_id'].astype('category').cat.codes
filtered_df['asin'] = filtered_df['asin'].astype('category').cat.codes

filtered_df.head()

   rating                                               text  user_id  asin
0     5.0  This is a great book with a lot of detail.  ON...        0  1655
1     5.0  Ladies 'n Gentlemen...we have another hit from...        1  5766
2     5.0  I ordered this book for my Kindle. Koontz and ...        1  5817
3     5.0  Absolutely loved this book!  Stephen King just...        1  5819
4     5.0  Another King satisfied reader~!  what can I sa...        1  5877

In [242]:
import gensim.downloader as api

word2vec_model = api.load('word2vec-google-news-300')

# Access word embeddings from the pre-trained model
vector = word2vec_model['word']

In [ ]:
import numpy as np
word2vec_model['<pad>'] = np.zeros(300)

In [317]:
%%time
max_length = 100
filtered_df['text'] = filtered_df['text'].astype('string')\
                                        .fillna('')\
                                        .str.split(' ')\
                                        .apply(lambda words: [word for word in words if word in word2vec_model.key_to_index])

filtered_df['text'] = filtered_df['text'].apply(
    lambda x: x[:max_length] + ['<pad>'] * (max_length - len(x)) if len(x) < max_length else x[:max_length]
)

CPU times: user 1.01 s, sys: 215 ms, total: 1.23 s
Wall time: 1.3 s

In [318]:
filtered_df['text']

0         [This, is, great, book, with, lot, ONE, CAUTIO...
1         [Ladies, have, another, hit, from, Stephen, th...
2         [I, ordered, this, book, for, my, Koontz, two,...
3         [Absolutely, loved, this, Stephen, King, just,...
4         [Another, King, satisfied, what, can, I, The, ...
                                ...
105975    [Funny, book, daughter, did, book, report, on,...
105976    [Lot, great, information, on, Use, it, almost,...
105977    [Love, this, book, <pad>, <pad>, <pad>, <pad>,...
105978    [7, year, old, loves, this, workbook, we, go, ...
105979    [we, all, him, he, chosen, Its, potter, I, lov...
Name: text, Length: 105980, dtype: object

In [219]:
import time
a = time.time()
for j in range(1000):
    req_list = [i for i in filtered_df['text'][j] if i in word2vec_model.key_to_index]
    if len(req_list):
        word2vec_model[req_list]
b = time.time() - a
print(f'time - {b/1000}')

time - 0.0004230670928955078

In [235]:
%%time
from torch.nn.utils.rnn import pad_sequence
max_length = 100
a = time.time()

w2v_tensor = [torch.from_numpy(word2vec_model[i]) for i in filtered_df['text'][0:2000] if len(i)!=0]
output = pad_sequence(w2v_tensor, batch_first=True, padding_value=0)

b = time.time() - a
print(f'time - {b/1000}')

time - 0.0005475971698760987
CPU times: user 324 ms, sys: 359 ms, total: 682 ms
Wall time: 548 ms

In [324]:
%%time
from torch.utils.data import Dataset, DataLoader


class RecSysDataset(Dataset):
    def __init__(self, df, word2vec_model, max_reviews):
        self.df = df
        self.word2vec_model = word2vec_model
        self.max_reviews = max_reviews

    def __len__(self):
        return len(self.df)
        
    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        
        user_reviews = self.df[self.df['user_id'] == row.user_id]['text']
        w2v_user_tensor = [torch.from_numpy(self.word2vec_model[i]) for i in user_reviews if len(i)!=0]
        user_tower_input = pad_sequence(w2v_user_tensor, batch_first=True, padding_value=0)

        item_reviews = self.df[self.df['asin'] == row.asin]['text']
        w2v_item_tensor = [torch.from_numpy(self.word2vec_model[i]) for i in item_reviews if len(i)!=0]
        item_tower_input = pad_sequence(w2v_item_tensor, batch_first=True, padding_value=0)

        target_size = (self.max_reviews, max_length, 300)
        user_tower_input = self._resize_tensors(user_tower_input, target_size)
        item_tower_input = self._resize_tensors(item_tower_input, target_size)

        return user_tower_input, item_tower_input, row['rating'], row['user_id'], row['asin']

    def _resize_tensors(self, input_tensor, target_size):

        # Resize the num_reviews if needed; TODO - change to random sampling? picking only first `max_reviews` number of reviews of the user or item
        tensor_size = input_tensor.shape
        if tensor_size[0] != target_size[0]:
            if tensor_size[0] < target_size[0]:
                diff = target_size[0] - tensor_size[0]
                padding = torch.zeros((diff, tensor_size[1], tensor_size[2]))
                output_tensor = torch.cat((input_tensor, padding), dim=0)
            else:
                output_tensor = input_tensor[:target_size[0]]
        else:
            output_tensor = input_tensor
        return output_tensor

CPU times: user 96 μs, sys: 258 μs, total: 354 μs
Wall time: 251 μs

In [325]:
%%time
# num_reviews, review_length, word_dim
# num_reviews, review_length, word_dim

# do we need to use negative sampling??
# padding a tensor?
# remove any words that are not present in the word2vec vocabulary

recsys_dataset = RecSysDataset(filtered_df, word2vec_model, 10)
dataloader = DataLoader(recsys_dataset, batch_size=32, shuffle=True)

for i, sample in enumerate(dataloader):
    if i > 2:
        break
    user_tower_input, item_tower_input, label, user_id, asin = sample
    print(user_tower_input.shape, item_tower_input.shape)

torch.Size([32, 10, 100, 300]) torch.Size([32, 10, 100, 300])
torch.Size([32, 10, 100, 300]) torch.Size([32, 10, 100, 300])
torch.Size([32, 10, 100, 300]) torch.Size([32, 10, 100, 300])
CPU times: user 4.17 s, sys: 901 ms, total: 5.07 s
Wall time: 1.4 s

In [289]:
%%time

source_pad = F.pad(output, pad=(0, 0, 0, 1000 - output.shape[1]))
source_pad.shape

CPU times: user 292 ms, sys: 1.45 s, total: 1.74 s
Wall time: 1.07 s

torch.Size([1993, 1000, 300])

In [ ]:
class NRCMA(nn.Module):
    def __init__(self, 
                 num_users, 
                 num_products,
                 num_conv_filters,
                 ):

In [326]:
user_tower_input.shape

nn.Conv2d(in_channels=1, out_channels=num_conv_filters, kernel_size=(word_embed_dim, 1), padding=0, bias=True)

torch.Size([32, 10, 100, 300])